name: Python UI autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select tests to run
        type: choice
        required: true
        default: smoke
        options:
          - All
          - Smoke
          - Regression

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: Check out repository with autotests
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run ALL tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest -v --alluredir=results
        continue-on-error: true
      - name: Run SMOKE suite
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -v -m smoke --alluredir=results
        continue-on-error: true
      - name: Run REGRESSUON suite
        if: "github.event.inputs.deployment_target == 'regression'"
        run: pytest -v -m regression --alluredir=results
        continue-on-error: true
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Install Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.32.0/allure-2.32.0.tgz && 
          sudo tar -zxvf allure-2.32.0.tgz -C /opt/ && 
          sudo ln -s /opt/allure-2.32.0/bin/allure /usr/bin/allure
      - name: Generate report
        run: allure generate -c -o _site
      - name: Save report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site
          retention-days: 3

  publish-report:
    name: Report publication
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
